### ISSUE TITLE
Overlapping scheduled function calls - Can't stop schedule 

### ISSUE THREAD

**Issue by jjfine** [juxt/tick#10]
I was trying to see the behavior when calls to a long-running scheduled function overlap. I thought it was working as expected: the scheduled function is called at every tick in the schedule even if another is running. However, I'm unable to stop the schedule. Code to reproduce the issue is below. The issue goes away when removing the `Thread/sleep` or reducing it to less than the schedule interval. Even calling `stop` during the sleep works.

For my use case, I'm working on preventing the scheduled function from doing any work when another is in progress so it's not really an issue for me. More just wondering if I'm doing something wrong here.

```
(require '[tick.schedule :as schedule])
(require '[tick.clock :as clock])
(require '[tick.timeline :as tl])
(require '[tick.core :as tick])

(defn wait [t]
  (println (format "waiting for 30s - %s" t))
  (Thread/sleep 30000)
  (println (format "done waiting - %s" t)))

(defn build-schedule [now]
  (let [evey-ten-secs (tl/periodic-seq now (tick/seconds 10))]
    (schedule/schedule wait
                       (tl/timeline evey-ten-secs))))

(def my-schedule
  (let [sch (build-schedule (clock/now))]
     (schedule/start sch (clock/clock-ticking-in-seconds))
     sch))

;; Wait a few seconds and then call:

(schedule/stop my-schedule)
```

**Comment by malcolmsparks** [comment]
Thanks for raising this issue Jeremy. There is going to be some overhaul of the scheduling code to merge in the new alpha API in incubation. I'll leave this issue open so that it gets properly fixed.

**Comment by tomelkin** [comment]
Same issue here.  Thanks for your efforts, @malcolmsparks

**Comment by malcolmsparks** [comment]
Thanks for this @tomelkin - I can confirm that this is a bug, thanks @jjfine for the test case which made repeating the problem straight-forward.

The current algorithm makes the assumption that there is only ever zero or one 'scheduled future' remaining. This is obviously a wrong assumption. The solution may be to shutdown the executor on stop. However, I can't see an obvious way of doing this without the pause functionality being affected. I would have to remove this feature, or find another way. Let me know if you have any ideas, I will do some thinking...

**Comment by tomelkin** [comment]
@malcolmsparks Scheduled jobs in my tests are shutting down no problem now.  Thanks for the fix!
