### ISSUE TITLE
Using tick with Clojurescript version "1.10.773"

### ISSUE THREAD

**Issue by amazing-Mantse** [juxt/tick#101]
The tick library still uses `joda-time` which has been deprecated. I am not sure if this is the cause of my issues.

But I am getting this error after the cljs upgrade  to `1.10.773`: 
 `Uncaught TypeError: Cannot read property 'Period' of undefined`

In the dev environment everything is okay. Advanced compilation is the one producing this issue.

I was also forced to install `@js-joda/core` in order for development to work.

**Comment by henryw374** [comment]
Hi amazing-Mantse, I'm guessing you are on an old version bc @js-joda/core is now used. Blog post about the change with links to cljs setup: http://widdindustries.com/tick-with-shadow-just-works/

**Comment by amazing-Mantse** [comment]
Thank you @henryw374 but I am using the latest version. It works fine in development. The error is only in prod.

**Comment by henryw374** [comment]
could you reproduce this in a git repo I can look at? Myself and others are using tick with advanced optimizations, with various build setups, so think it will likely be some setup issue on your end.

**Comment by amazing-Mantse** [comment]
Still seeing this issues on my local machine. I deployed to test environment and there, that error seems to be gone. Now I have a new React related error. So something fishy with my configs then.

**Comment by henryw374** [comment]
ok good luck. pls reopen if there's a problem I could recreate
