### ISSUE TITLE
pause / resume

### ISSUE THREAD

**Issue by kwladyka** [juxt/tick#11]
```clojure
(def foo
  (let [timeline (-> (periodic-seq (now) (seconds 2))
                     (timeline))]
    (schedule (fn [_] (println "foo")) timeline)))

(defn bar []
  (start foo (clock-ticking-in-seconds))
  (stop foo)
  (schedule/pause foo)
  (schedule/resume foo))
```

When `pause` foo for a while and `resume` it will instantly run foo many times, because of "missed" points of time while paused. It shouldn't work like that. It should start from the point of time when `resume`. So points of time during pause should be as launched. pause/resume is not usable at that moment, because of that issue. Unless i miss something.

**Comment by malcolmsparks** [comment]
Thanks for raising this.

The default behaviour is to avoid missed triggers, even if they are late. The rationale here is that you may be scheduling some important jobs that must not be missed, but you may need to temporarily pause processing (to fix something perhaps).

For your use-case, I think it is better to stop the schedule and restart with a new timeline. After stop, the remaining timeline is in the state atom in the `SchedulingTicker` record. That can be used as an argument to `tick.schedule/schedule` to create a new instance.

I hope this explains the intention, happy to discuss further on this issue.

**Comment by kwladyka** [comment]
It is probably worth to mention it in the doc. It is not intuitive it is assumption of the `tick`.

I am curious if there is somebody who really want such behaviour when use pause / resume. But maybe I can't imagine such situation.

For now i use `stop` and recreate everything again with `start`.

I can't use remaining timeline, because between `stop` and `start` can be days of "pause". So again it will run many times after start.

Offtopic: I really miss option to prevent run job more than once. Like systems synchronisation. I have to write my own solution to not run function twice during "cron". It is simple with `atom` or `async`, but still looks like something really common needed here. Further I would like to know when jobs finish after `stop` to not run `start` new schedule while old one still working.

**Comment by henryw374** [comment]
Scheduling has been removed from tick now. Chime lib might have what you need.
