### ISSUE TITLE
Publish API docs

### ISSUE THREAD

**Issue by plexus** [juxt/tick#12]
@martinklepsch suggested it would be helpful to have API docs published for Tick.

There's a handy script that I and others have been using that makes it trivial to generate docs with codox, and publish them to `gh-pages`. I explain things a bit more [in this thread](https://clojureverse.org/t/which-libraries-are-in-need-of-accessible-api-docs/1109?u=plexus).

Would you be interested to have this for Tick? If so I can provide a PR that adds the script, codox, and a link to the API docs from the README. After that it's up to you to simply run `./generate_docs`.

Thanks!

**Comment by malcolmsparks** [comment]
That would be lovely, thanks!

**Comment by henryw374** [comment]
Closing as this ticket looks out of date.
