### ISSUE TITLE
between works with an instant and a zoned date time, but not vice versa

### ISSUE THREAD

**Issue by madstap** [juxt/tick#123]
Is this a bug?

```clojure
(require '[tick.alpha.api :as tick])

;; This works
(tick/between (tick/instant) (tick/zoned-date-time))

;; But the reverse doesn't
(tick/between (tick/zoned-date-time) (tick/instant))

;; 1. Caused by java.time.DateTimeException
;; Unable to obtain ZoneId from TemporalAccessor:
;; 2020-11-12T21:59:30.622034Z of type java.time.Instant

;; This is a workaround
(tick/between (tick/instant (tick/zoned-date-time)) (tick/instant))
```

**Comment by madstap** [comment]
Is this expected behavior? I expected between to work with any 2 values of types that represent a point on the timeline.

**Comment by henryw374** [comment]
It is based on https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#between-java.time.temporal.Temporal-java.time.temporal.Temporal- 

except that for some (perhaps should be more) entities tick coerces the second arg to the type of the first, so it accepts a wider range of arg types.
