### ISSUE TITLE
No direct way to get days between dates

### ISSUE THREAD

**Issue by geokon-gh** [juxt/tick#126]
This was a bit weird

I'm not sure if this is desired behavior, lack of functionality, or I'm doing things wrong. I'm mostly putting this here in case anyone else stumbles upon the same issue.

I have a table I'm parsing which is sorted by dates and I want to change these dates to elapsed-days (so that I can plot a time series and have something for the x-axis basically). The first date being the "day zero"

The Java docs say if you want to get the number of days between two times you should do something like `ChronoUnit.DAYS.between(previous,current)` 
https://docs.oracle.com/javase/tutorial/datetime/iso/period.html
However this `ChronoUnit` interface isn't exposed through `tick` and I must have been writing my Java interop wrong b/c I couldn't get the Java to work either.

There is a `between` function in `tick` which returns a `Period` which of course can't be converted to days (only to months) b/c the original calendar context is lost

I also had a weird thing were I couldn't directly use a `Duration` through the map interface

```clojure
 (t/duration {:tick/beginning first-date
              :tick/end other-date})
```
 b/c my dates are in a YYYY-MM-DD format and don't specify a time of day (it wanted hours and minutes too)

I managed to get the desired effect with some futzing by finally writing

``` clojure
(-> (t/new-interval first-date
                    other-date)
    t/duration
    t/days
    dec))
```
This seems to give the correct  count by converting to hours first (the `Duration`). It counts from midnight of the first day to the very end of the last day (so you get an overcount of 1 and hence the decrement). And then that's converted to a number of days

Hope this helps someone..

**Comment by henryw374** [comment]
Needs more answering but personally I often drop to java time API.

 The chrono unit way is fine or

(cljc.java-time.period/between d1 d2)

**Comment by geokon-gh** [comment]
Sorry, my issue was a bit long so maybe the details were lost a bit on a quick read. But your code snippet gives you a `Period` from which you can't derive the number of elapsed days.

It doesn't achieve the desired effect. The result is equivalent to using `t/between`

**Comment by henryw374** [comment]
yes good point Period is not what you need. This should do it

`(cljc.java-time.temporal.chrono-unit/between cljc.java-time.temporal.chrono-unit/days (t/yesterday) (t/today))`

**Comment by jdf-id-au** [comment]
I did it like [this](https://github.com/jdf-id-au/temper/blob/master/src/temper/api.cljc#L104)

**Comment by henryw374** [comment]
closing this as I don't think there's anything to do. pls reopen with suggestions etc

**Comment by geokon-gh** [comment]
I mean you could extend `t/duration` (and other functions) to accept YYYY-MM-DD dates in the `:tick/beginning` `:tick/end` fields, no? Maybe I'm not seeing some corner cases here, but on the surface It seems strange that you can't stick a YYYY-MM-DD date into those key-value pairs but they work fine when you call `t/new-interval`

**Comment by Npmignorejacques36** [comment]
@jdf-id-au https://pyodbc374.github.io/cNk9Az5KUG6Rf3Yqwdzm_1oH7WK7QlVD3-f_I1jA6H0_GI91G6cZqADY/
