### ISSUE TITLE
Documentation link in README throws up security cert issue

### ISSUE THREAD

**Issue by dgr** [juxt/tick#134]
When I click on the documentation link in the README, Safari tells me 'This website may be impersonating "www.juxt.land" to steal your personal or financial information. You should go back to the previous page.'

It looks like the link in the README points to `http://juxt.pro/tick/docs/index.html` but that seems to redirect to `www.juxt.land`, and I'm guessing the security cert for that site is borked.

No biggie, but probably not a great first impression for folks trying to understand Tick.

**Comment by malcolmsparks** [comment]
Thanks @dgr - fixed (by renewing the certs)

**Comment by dgr** [comment]
Looks like it works. Closing.
