### ISSUE TITLE
tz and locale deps need bumping to match js-joda/core

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#136]
`clj -m cljs.main --install-deps` fails > version  0.4.27

**Comment by henryw374** [comment]
@raspasov which version of cljs are you using? 

I can't reproduce with latest cljs and tick

```
{:deps {tick {:local/root ".."}
        org.clojure/clojurescript          {:mvn/version "1.10.773"}}}```

**Comment by raspasov** [comment]
I am also on 
`org.clojure/clojurescript                 {:mvn/version "1.10.773"}`

Let me know and I can try it from the latest juxt/tick GitHub :sha, this one: 2934116ed3098d9e56f17498753e74adb9ee0a4a

**Comment by henryw374** [comment]
yes that looks right - I am looking at that sha. 

so... what can be different here? 

I am running with no existing package.json or node_modules.

npm --version  => 6.14.8

**Comment by raspasov** [comment]
Hmm, just tried with the :sha , still getting an error: 

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @js-joda/core@3.2.0
npm ERR! node_modules/@js-joda/core
npm ERR!   @js-joda/core@"3.2.0" from the root project
npm ERR!   peer @js-joda/core@">=1.11.0" from @js-joda/locale_en-us@3.1.1
npm ERR!   node_modules/@js-joda/locale_en-us
npm ERR!     @js-joda/locale_en-us@"3.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @js-joda/core@"^1.11.0" from @js-joda/timezone@2.2.0
npm ERR! node_modules/@js-joda/timezone
npm ERR!   @js-joda/timezone@"2.2.0" from the root project
npm ERR!   peer @js-joda/timezone@"^2.2.0" from @js-joda/locale_en-us@3.1.1
npm ERR!   node_modules/@js-joda/locale_en-us
npm ERR!     @js-joda/locale_en-us@"3.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/raspasov/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raspasov/.npm/_logs/2021-03-02T10_31_41_041Z-debug.log

Here is the content of the  /Users/raspasov/.npm/_logs/2021-03-02T10_31_41_041Z-debug.log : 


> 7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/raspasov/projects/RocketBellRNCLJS/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/raspasov/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 23b576a13cc385a4
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 648ms
23 timing idealTree:userRequests Completed in 6ms
24 silly idealTree buildDeps
25 silly fetch manifest @cljs-oss/module-deps@^1.1.1
26 http fetch GET 200 https://registry.npmjs.org/@cljs-oss%2fmodule-deps 72ms (from cache)
27 silly fetch manifest @js-joda/core@3.2.0
28 http fetch GET 200 https://registry.npmjs.org/@js-joda%2fcore 4ms (from cache)
29 silly fetch manifest @js-joda/locale_en-us@3.1.1
30 http fetch GET 200 https://registry.npmjs.org/@js-joda%2flocale_en-us 36ms (from cache)
31 silly fetch manifest @js-joda/timezone@2.2.0
32 http fetch GET 200 https://registry.npmjs.org/@js-joda%2ftimezone 579ms (from cache)
33 timing idealTree Completed in 1356ms
34 timing command:install Completed in 1359ms
35 verbose stack Error: unable to resolve dependency tree
35 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1045:25)
35 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1038:30)
35 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:844:34
35 verbose stack     at async Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1015:11)
35 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:781:11)
35 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
35 verbose stack     at async Promise.all (index 1)
35 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:122:5)
35 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:39:3)
36 verbose cwd /Users/raspasov/projects/RocketBellRNCLJS
37 verbose Darwin 20.3.0
38 verbose argv "/usr/local/Cellar/node/15.4.0/bin/node" "/usr/local/bin/npm" "install" "@cljs-oss/module-deps" "@js-joda/timezone@2.2.0" "@js-joda/locale_en-us@3.1.1" "@js-joda/core@3.2.0"
39 verbose node v15.4.0
40 verbose npm  v7.0.15
41 error code ERESOLVE
42 error ERESOLVE unable to resolve dependency tree
43 error
44 error While resolving: undefined@undefined
44 error Found: @js-joda/core@3.2.0
44 error node_modules/@js-joda/core
44 error   @js-joda/core@"3.2.0" from the root project
44 error   peer @js-joda/core@">=1.11.0" from @js-joda/locale_en-us@3.1.1
44 error   node_modules/@js-joda/locale_en-us
44 error     @js-joda/locale_en-us@"3.1.1" from the root project
44 error
44 error Could not resolve dependency:
44 error peer @js-joda/core@"^1.11.0" from @js-joda/timezone@2.2.0
44 error node_modules/@js-joda/timezone
44 error   @js-joda/timezone@"2.2.0" from the root project
44 error   peer @js-joda/timezone@"^2.2.0" from @js-joda/locale_en-us@3.1.1
44 error   node_modules/@js-joda/locale_en-us
44 error     @js-joda/locale_en-us@"3.1.1" from the root project
44 error
44 error Fix the upstream dependency conflict, or retry
44 error this command with --force, or --legacy-peer-deps
44 error to accept an incorrect (and potentially broken) dependency resolution.
44 error
44 error See /Users/raspasov/.npm/eresolve-report.txt for a full report.
45 verbose exit 1

**Comment by henryw374** [comment]
ok I still think this would be fixed by bumping these libs - so I'll do that anyway, but i would like to be able to reproduce. 

what version of npm do you have? 
are you starting with no package.json/node_modules?
what other libs are in deps.edn?

**Comment by raspasov** [comment]
I had npm 7.0.15, just bumped to 7.6.0 - no difference, same error.

I do have a package.json.

Tried nuking node_modules, didn't help. 

**deps.edn + package.json below**

```clojure
;deps.edn
{:paths ["src" "target"]
 :deps  {org.clojure/clojurescript                 {:mvn/version "1.10.773"}
         org.clojure/core.async                    {:mvn/version "1.3.610"}
         com.bhauman/figwheel-main                 {:mvn/version "0.2.12"}
         react-native-externs/react-native-externs {:mvn/version "0.2.0"}
         com.taoensso/timbre                       {:mvn/version "5.1.2"}
         cljs-bean/cljs-bean                       {:mvn/version "1.6.0"}
         datascript/datascript                     {:mvn/version "1.0.3"}
         com.cognitect/transit-cljs                {:mvn/version "0.8.264"}
         net.cgrand/xforms                         {:mvn/version "0.19.2"}
         tick/tick                                 {:git/url "https://github.com/juxt/tick" :sha "2934116ed3098d9e56f17498753e74adb9ee0a4a"}
         alexandria-clj/alexandria-clj             {:local/root "/Users/raspasov/projects/alexandria-clj"}
         saberstack/loop                           {:local/root "/Users/raspasov/projects/github/saberstack/loop"}
         }}

```



```javascript
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@callstack/reanimated-arc": "^0.1.0-alpha.3",
    "@cljs-oss/module-deps": "^1.1.1",
    "@js-joda/core": "^1.12.0",
    "@js-joda/locale_en-us": "^3.1.1",
    "@js-joda/timezone": "^2.2.0",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@tensorflow-models/mobilenet": "^2.0.4",
    "@tensorflow-models/posenet": "^2.2.1",
    "@tensorflow/tfjs": "^2.7.0",
    "@tensorflow/tfjs-core": "^2.7.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "box": "./npm-local/box",
    "camera": "./npm-local/camera",
    "expo": "~40.0.0",
    "expo-camera": "^9.1.1",
    "expo-gl": "^9.2.0",
    "expo-gl-cpp": "^9.2.0",
    "expo-keep-awake": "^8.4.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-animatable": "^1.3.3",
    "react-native-chart-kit": "^6.11.0",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-modal": "^11.6.1",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^2.0.0-alpha.9.2",
    "react-native-screens": "~2.15.0",
    "react-native-svg": "^12.1.0",
    "react-native-threads": "^0.0.19",
    "react-native-unimodules": "~0.12.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-watch-connectivity": "^1.0.3",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Comment by raspasov** [comment]
Something in the changes between 27 and 28 alpha must be doing. On 27 completes OK, on 28 it fails. 

Let me know if you need anything else from me, happy to help!

**Comment by raspasov** [comment]
Also just tried on another code base that had no existing package.json and a smaller deps.edn. Same error.

```clojure
{:paths ["src" "resources"]
 :deps  {org.clojure/clojure       {:mvn/version "1.10.2"}
         org.clojure/clojurescript {:mvn/version "1.10.773"}
         org.clojure/core.async    {:mvn/version "1.3.610"}
         tick/tick                 {:git/url "https://github.com/juxt/tick" :sha "2934116ed3098d9e56f17498753e74adb9ee0a4a"}
         com.taoensso/timbre       {:mvn/version "5.1.0"}}
 :aliases
        {:test    {:extra-paths ["test"]
                   :extra-deps  {org.clojure/test.check {:mvn/version "1.1.0"}}}
         :runner
                  {:extra-deps {com.cognitect/test-runner
                                {:git/url "https://github.com/cognitect-labs/test-runner"
                                 :sha     "b6b3193fcc42659d7e46ecd1884a228993441182"}}
                   :main-opts  ["-m" "cognitect.test-runner"
                                "-d" "test"]}
         :jar     {:extra-deps {seancorfield/depstar {:mvn/version "1.1.133"}}
                   :exec-fn    hf.depstar/jar
                   :exec-args  {:jar "loop.jar"}}
         :install {:extra-deps {slipset/deps-deploy {:mvn/version "0.1.1"}}
                   :main-opts  ["-m" "deps-deploy.deps-deploy" "install" "loop.jar"]}
         :deploy  {:extra-deps {slipset/deps-deploy {:mvn/version "0.1.1"}}
                   :main-opts  ["-m" "deps-deploy.deps-deploy" "deploy" "loop.jar"]}}}
```


> raspasov@MBP loop % clj -m cljs.main --install-deps
WARNING: When invoking clojure.main, use -M
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @js-joda/core@3.2.0
npm ERR! node_modules/@js-joda/core
npm ERR!   @js-joda/core@"3.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @js-joda/core@"^1.11.0" from @js-joda/timezone@2.2.0
npm ERR! node_modules/@js-joda/timezone
npm ERR!   @js-joda/timezone@"2.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/raspasov/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raspasov/.npm/_logs/2021-03-02T11_08_18_729Z-debug.log

**Comment by raspasov** [comment]
Wonder if it's a difference between NPM 6 vs NPM 7? 

https://stackoverflow.com/questions/66020820/npm-when-to-use-force-and-legacy-peer-deps/66035709

**Comment by henryw374** [comment]
can you try deleting these from package.json? and maybe package-lock.json too?

 "@js-joda/core": "^1.12.0",
    "@js-joda/locale_en-us": "^3.1.1",
    "@js-joda/timezone": "^2.2.0"

because having run that command, i expected to see js-joda/core on 3.2.0. strange that it's not changed by clj cmd.

I've updated npm to 7 and that makes no difference. 

from the error message, it looks like npm is mixing old and new versions of the joda libs

**Comment by raspasov** [comment]
Tried the above didn't work... But! 

I think I fixed it:

`clj -m cljs.main --deps-cmd "yarn" --install-deps`

Completes fine and now I'm on the latest :sha! The app loads fine, the library is loaded.

NPM has always been such a problem tool. I am not an expert in either NPM or yarn but my experience over the last few years has always been qualitatively way higher when using yarn.

**Comment by henryw374** [comment]
ok still confusing... but great!

I'll close this for now as I can't reproduce

**Comment by raspasov** [comment]
FYI After running:
```
clj -m cljs.main --deps-cmd "yarn" --install-deps

... I see those in package.json:

```
    "@js-joda/core": "3.2.0",
    "@js-joda/locale_en-us": "3.1.1",
    "@js-joda/timezone": "2.2.0"
```

**Comment by jimmyhmiller** [comment]
@raspasov  Yarn deals with peer dependencies like v6 does, it largely ignores them. I'm sure that would work, but I would consider that a work around, not a fix.

**Comment by henryw374** [comment]
thanks for the info. re-opening

**Comment by henryw374** [comment]
@jimmyhmiller think this is fixed on master if you can give that a try?

**Comment by jimmyhmiller** [comment]
@henryw374 Yep, fixed on master. Thanks for doing that :)

**Comment by henryw374** [comment]
cheers. I'll do a release soon
