### ISSUE TITLE
Question: start of week

### ISSUE THREAD

**Issue by spacegangster** [juxt/tick#138]
Not an issue. Perhaps out of tick's scope, just want to be sure.

I scanned tick's docs and didn't find an entry on getting a beginning of a unit of time (apart from today).
My favourite (peskiest) unit of time is week, which can have different start day depending on the culture.
E.g. 2021-03-01 (March 1st 2021) is a Monday, so it's an ISO week start. But some countries would say that its week started on 2021-02-28 and some that it started on 2021-02-27. 

Do you support or plan to support this culture-dependent little pest and the unit of time flooring / ceiling shorthands?

Cheers!

**Comment by henryw374** [comment]
Interesting topic, I didn't know how that would work - found this answer https://stackoverflow.com/a/28454044/1700930 for how to do it with java.time. 

I think it's probably pretty rarely needed so I think leaving it out of tick is fine - users can use java.time directly if they need it.

**Comment by spacegangster** [comment]
Understandable.
Have a nice day!
