### ISSUE TITLE
ClojureScript: Protocol IBetween not extended for java.time.LocalTime

### ISSUE THREAD

**Issue by friemen** [juxt/tick#142]
tick.core Namespace extends protocol IBetween.

An expression like
`(t/between (t/new-time 11 0 0) (t/new-time 11 30 0))`
fails, because there is no implementation of LocalTime.

After I extend the protocol myself with this expression
```
(extend-protocol tick.protocols/IBetween
          java.time.LocalTime
          (between [v1 v2] (cljc.java-time.duration/between v1 v2)))
```
the t/beween invocation yields the desired result.

By default, tick.core should implement IBetween also for LocalTime.

**Comment by henryw374** [comment]
is this just clojurescript though?

**Comment by friemen** [comment]
Yes, only ClojureScript is affected. The same expression works fine on the JVM.
In ClojureScript I receive `#object[Error Error: No protocol method IBetween.between defined for type object: 11:00]`
