### ISSUE TITLE
Add function to test if a time is contained within an interval

### ISSUE THREAD

**Issue by dcj** [juxt/tick#147]
Something like this:
```
(defn contained-by-interval?
  [t {:keys [tick/beginning tick/end] :as i}]
  (and (t/<= beginning t) (t/< t end)))
```
This code assumes that `:tick/beginning` is an inclusive bound, and `:tick/end` is an exclusive bound (see issue #148)

**Comment by henryw374** [comment]
`coincident?` does this I think. please reopen if not
