### ISSUE TITLE
State/clarify in the documentation if interval bounds are inclusive and/or exclusive

### ISSUE THREAD

**Issue by dcj** [juxt/tick#148]
AFAICT  the `:tick/beginning` bound is inclusive, and `:tick/end` is exclusive, regardless, the truth should be stated/documented

**Comment by henryw374** [comment]
My understanding is that it is inclusive. although see #178  - currently it is different for different entities.

fyi  @malcolmsparks

**Comment by henryw374** [comment]
the bounds will be both inclusive when the following is released:

https://github.com/juxt/tick/commit/481c7bfb5a479e7635fe290dab1a62d65ab75e0b#diff-04bf5ae20c3b204c749b77792d9535bbcfdd88c9ea4441493d259beb98ffd3a9R46

**Comment by henryw374** [comment]
fixed in 0.7.0

**Comment by dcj** [comment]
I fully support this change, but caution that a careful review of the interval-calculus comparators might be in order.  I have no proof that any are incorrect, but if the interval bounds "clusivity" was in any way ambiguous or inconsistent previously, there may be an impact

**Comment by henryw374** [comment]
Thanks, it was just the bounds function returned inconsistent clusiveness results for different types, e.g .bounds of a year vs date vs year-month. 

the comparators should all be as per Allen's algebra - and have not changed
