### ISSUE TITLE
More polymorphic <,>, max, min and the missing 'coincide'

### ISSUE THREAD

**Issue by tamasjung** [juxt/tick#15]
Wouldn't it make sense everything coercible to Instant (ZondedDT, the good old java.util.Date, maybe even String and Number) be comparable with each other accepting as a second parameter for <,>, min, max? This raises the question, although a bit independent, of having new, missing op in ITimeComparision like 'same-instant' or 'coincide'. (Well, for non-locals.)

**Comment by malcolmsparks** [comment]
Great idea. That makes a lot of sense to me right now.

**Comment by SevereOverfl0w** [comment]
I just ran into this also with `(t/< (t/zoned-date-time) (t/instant))`

**Comment by henryw374** [comment]
pr that's working towards this: https://github.com/juxt/tick/pull/140

**Comment by henryw374** [comment]
fixed in c932146
