### ISSUE TITLE
Returns negative durations

### ISSUE THREAD

**Issue by rosejn** [juxt/tick#153]
Before discovering the t/duration function that I can call with an interval I was using between, and I noticed that if I called (between end beginning) I got a negative number, where with (between beginning end) it is positive.  It seems like between should always return a positive number no?

https://github.com/juxt/tick/blob/f47c3efd7f56f8ca59cb1f960d731d199217f986/src/tick/core.cljc#L910

**Comment by henryw374** [comment]
I don't think so. As with most things `tick`, it tries keep the behaviour of java.time intact, to  keep things as straightforward as possible.

Closing, but pls reopen if there's more to discuss.
