### ISSUE TITLE
cljs version 1.10.891 and foreign lib problem when running tick tests

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#155]
tick uses olical/cljs-test-runner lib, which when combined with this version of cljs does some further munging of foreign code which breaks the js
 (you will see the resulting js will error on load, bc property names within js-joda-timezone have been renamed)

@AndreaCrotti tick could use kaocha-cljs2 now afaik?

**Comment by AndreaCrotti** [comment]
In theory  yes, just need to figure out how to configure circleci to run funnel & co, and get it working.

**Comment by henryw374** [comment]
fixed. tick is now using kaocha-cljs2
