### ISSUE TITLE
Fix next, next-or-same, previous, previous-or-same to work with day-of-week

### ISSUE THREAD

**Issue by rafd** [juxt/tick#161]
I tried using `previous-or-same` as follows: 
```clj
(t/previous-or-same (t/today) t/MONDAY)
```
But I get the error: 
`No protocol method IExtraction.day-of-week defined for type object: MONDAY` (cljs)
`No implementation of method: :day-of-week of protocol: #'tick.protocols/IExtraction found for class: java.time.DayOfWeek` (clj)

`next`, `next-or-same`, `previous`, `previous-or-same` all call `(p/day-of-week __`) on the input https://github.com/juxt/tick/blob/9b4475db4aebc5c2d2ded82357b2862400ef0213/src/tick/core.cljc#L506-L508

But, `DayOfWeek` does not implement the `IExtraction` `day-of-week` protocol.

https://github.com/juxt/tick/blob/9b4475db4aebc5c2d2ded82357b2862400ef0213/src/tick/core.cljc#L323-L326

Presumably, it _should_ implement the protocol and return itself?
Or, should I be doing something else in my code example?

The following made my code work:
```clj
(extend-protocol tick.protocols/IExtraction
  java.time.DayOfWeek
  (day-of-week [d] d))
```

**Comment by henryw374** [comment]
looks good thanks
