### ISSUE TITLE
Function `tick.core/parse-day` is not matching Thursday correctly

### ISSUE THREAD

**Issue by retro** [juxt/tick#163]
I have an API call that returns shortened day names (mon tue wed thu fri sat sun), and Thursday is not correctly matched because `s` is included in the first part of the regex:

https://github.com/juxt/tick/blob/master/src/tick/core.cljc#L127

**Comment by henryw374** [comment]
hmm. The 's' is intentional I am pretty sure - it may be uk-specific. I would accept a pr to also accept 3-letter weekday names if that's what you need: mon,tue,wed,thu,fri,sat,sun.

An alternative I think would be to create a formatter to parse these.

**Comment by henryw374** [comment]
I added a doc string to explain. see what you think: https://github.com/juxt/tick/blob/master/src/tick/core.cljc#L123

**Comment by retro** [comment]
@henryw374 I made a mistake, I was referring to `r` being in the first part of the regex. But, I do think that docstring solves this problem, since it does make sense to write a project specific parser.

**Comment by henryw374** [comment]
Ok cheers
