### ISSUE TITLE
bug or feature? *clock* value cached default time zone.

### ISSUE THREAD

**Issue by kwladyka** [juxt/tick#165]
```clojure
(TimeZone/setDefault (TimeZone/getTimeZone "UTC"))
```

```
(tick/current-zone)
=> #time/zone"Europe/Warsaw"
(tick/zone)
=> #time/zone"Europe/Warsaw"
```

This is happening when loading the `tick.core` namespace.
```clojure
(def ^{:dynamic true} *clock* (cljc.java-time.clock/system-default-zone))
```

Depends if the namespace will be loaded before / after `(TimeZone/setDefault (TimeZone/getTimeZone "UTC"))` the tick `*clock*` will be `UTC` or different value.

I can be totally wrong, because I don't feel I am Java time expert, but this value shouldn't be cached. If it has to, then should be pointed out in documentation to overwrite this value.

PS I am reporting this, because it was very unexpected for me and I could make serious costly mistake. The assumption is system work in `UTC` always.

**Comment by henryw374** [comment]
hmm, tbh I only ever set jvm timezone via system prop and never change it within a running program. 

the *clock* thing I just use for testing. 

what's your use case here?

**Comment by kwladyka** [comment]
> the clock thing I just use for testing.

Oh do you mean it doesn't really make a difference?

It affects at least `(tick/current-zone)`, so I though it matters.

My case is the system needs to work only and only in `UTC` and can't work in different timezone even for 1 second. Sure the UTC needs to be set in system, but I was trying to make extra safety if this failed one day.

Just I didn't expect the time zone is cached. That is all.

You can do with this ticket what you want. Even close is it.

**Comment by henryw374** [comment]
I mean in testing I often want to set the clock to something specific and the clock is handy for that. There is the with-clock macro to do that.

As I say I would never set default tz within a running program, so I don't see an issue here. Plz reopen if needed
