### ISSUE TITLE
Compiler error "no dispatch macro for: ?" in RC6

### ISSUE THREAD

**Issue by svdo** [juxt/tick#170]
First of all of course many thanks for Tick 🙏 !

This morning I upgraded tick from RC5 to RC6, and now I'm getting a compiler error when building my uberjar:

```clojure
{:error "unable to copy file", :name "data_readers.cljc", :exception java.lang.RuntimeException, :message "No dispatch macro for: ?"}
```

The file `data_readers.cljc` is ours, we define a read `#tap>` that we can put pretty much anywhere in our code to have the things after it tapped. (Very convenient 😄 ) I have no idea what this error means and what causes it or how to solve it. Since it was triggered by the update of Tick, I thought I'd ask over here. Thanks for looking into this!!

**Comment by henryw374** [comment]
ok but does building the uberjar involve compiling cljs? 

if not, how are you building the uberjar? can you get a stack trace?

**Comment by henryw374** [comment]
we have some places using depstar on ver 2.0.26 and I think that is building ok. 

also some places using tools.build and that seems fine too.

**Comment by svdo** [comment]
Right, depstar doesn't seem to be the issue indeed.

**Comment by henryw374** [comment]
i think it is depstar  - and this issue only crops up when there is more than one data_readers.clj/c file on the classpath.

https://github.com/seancorfield/depstar/blob/develop/src/hf/depstar/uberjar.clj#L110

it is trying to read the edn, but has not set flag to e.g. just read :clj

**Comment by archaic** [comment]
Hi, I am getting the same issue with tools.build (when usinging multiple data_readers), this only happened today when I updated deps ---
Execution error at clojure.tools.build.tasks.uber/conflict-data-readers (uber.clj:90).
No dispatch macro for: ?

Digging deeper now.

**Comment by archaic** [comment]
I don't think this is the problem or tick, I think its more a problem in tools.build. To fix it to be able to compile an uberjar, I had to use read-string instead of edn/read-string:

in build.clj (using build-clj)

(defn install
  [opts]
  (-> opts
     (assoc :uber-file "foo.jar")
     (merge {:conflict-handlers
             {"^data_readers.clj[cs]?$"
              (fn [{:keys [path in ^java.io.File existing]}]
                (let [existing-str (slurp existing)
                      existing-reader-fns (read-string {:read-cond :allow} existing-str)
                      append-reader-fns (read-string {:read-cond :allow} (#'clojure.tools.build.tasks.uber/stream->string in))
                      reader-str (with-out-str (pprint/pprint (merge existing-reader-fns append-reader-fns)))]
                  {:write {path {:string reader-str}}}))}
             :transitive true})
     corfield.build/uber))

**Comment by henryw374** [comment]
Ok thanks. Have you made an issue in tools.build?

**Comment by archaic** [comment]
Nope, they don't make it easy to raise issues!

**Comment by henryw374** [comment]
oh it's jira. I already have jira account. I can raise issue if you prefer?

**Comment by henryw374** [comment]
raised https://clojure.atlassian.net/browse/TBUILD-32

**Comment by henryw374** [comment]
well, it's a long story. how long have you got? 

tick depends on a ver of time-literals that uses reader conditionals https://github.com/henryw374/time-literals/blob/master/src/data_readers.cljc

reader conditionals in data_readers.cljc has always been supported by clojure, and should have been in clojurescript but was not until the last release.

previously time-literals avoided using conditionals by using a workaround/hack. https://github.com/henryw374/time-literals/issues/3

**Comment by svdo** [comment]
Ah right, I understand, thanks for your explanation!

**Comment by puredanger** [comment]
I'll work on the tools.build error today, thanks. For reference, you can always file tools.build issues as questions at https://ask.clojure.org (like https://ask.clojure.org/index.php/12017/exception-in-ednreaderdispatchreader)

**Comment by henryw374** [comment]
Thanks Alex
