### ISSUE TITLE
.plusDays support through DST

### ISSUE THREAD

**Issue by juskrey** [juxt/tick#174]
Native Java `.plusDays` method, when result passes through DST threshold, handles next day's time correctly,effectively adding 23 hours instead of 24:
```clojure
(.plusDays (t/zoned-date-time "2022-03-13T00:00-05:00[America/New_York]") 1)
=> #time/zoned-date-time"2022-03-14T00:00-04:00[America/New_York]"
```

While in tick it seems impossible to have the same result using idiomatic call:
```clojure
(t/>> (t/zoned-date-time "2022-03-13T00:00-05:00[America/New_York]")
         (t/new-duration 1 :days))
=> #time/zoned-date-time"2022-03-14T01:00-04:00[America/New_York]"
```
It adds 24 hours instead of 23.

The same problem I see with interval division by day(s) - when passing through DST change time, it shifts by one hour.

**Comment by henryw374** [comment]
use a period instead

(t/>> (t/zoned-date-time "2022-03-13T00:00-05:00[America/New_York]")
  (t/new-period 1 :days))

a Duration of 1 day is always 24 hours. java.time shouldn't have mixed Duration with days in IMO but there we go. Tick doesnt try to fix the bugs of java.time

**Comment by juskrey** [comment]
Thank you, that works for me!
