### ISSUE TITLE
tick/coincident? returns true given a date and an interval of dates

### ISSUE THREAD

**Issue by Jacob-Kroeze** [juxt/tick#176]
I expected false
```
(tick/coincident? (tick/date "2020-09-30") (interval/new-interval (tick/date "2017-11-15") (tick/date "2020-05-16")))
;;=> true
```

This works for me: I expected nil
```
(interval/concur (tick/date "2020-09-30") (interval/new-interval (tick/date "2017-11-15") (tick/date "2020-05-16")))
;;=> nil
```

**Comment by dcj** [comment]
Looking at the source of `tick/coincident?` it is not obvious to me that it expects/supports the first argument to be a non-interval.

**Comment by henryw374** [comment]
@Jacob-Kroeze I think you had the arguments the wrong way around. 

the first arg is the interval that might or might not contain the second arg, the event. 

I have changed the implementation of coincident? including the arg names to make it a bit clearer. see https://github.com/juxt/tick/blob/master/src/tick/core.cljc#L1393

also added some tests which serve as examples  https://github.com/juxt/tick/blob/master/test/tick/api_test.cljc#L357
