### ISSUE TITLE
tick/end seems inconsistent for different entities

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#178]
(-> (t/beginning (t/date))
    (t/>> (t/new-duration 24 :hours)))

is equal to (t/end (t/today)). that seems to make sense that it takes us to the start of the next day because the day is 24 hours long. 

but, 

(t/end (t/year 2022))
=> #time/date-time"2022-12-31T23:59"

seems inconsistent with that, it takes us almost a year forward from the start of the year, but not quite.

**Comment by zeitstein** [comment]
I understand that perspective. For me, if I was considering a year as an interval, the second example makes sense – the end point of the year is just before the next year.

I think this is related to #148 – interval end should be treated as excluded `[beginning end)` (by users, I guess).

**Comment by henryw374** [comment]
on branch below, year, yearmonth and localdate beginning/end have been made consistent - all end inclusive 

see https://github.com/juxt/tick/commit/481c7bfb5a479e7635fe290dab1a62d65ab75e0b#diff-04bf5ae20c3b204c749b77792d9535bbcfdd88c9ea4441493d259beb98ffd3a9R46

**Comment by henryw374** [comment]
fixed in 0.7.0
