### ISSUE TITLE
Help with example countdown timer

### ISSUE THREAD

**Issue by hjer** [juxt/tick#181]
Hi! I'm writing a super simple countdown clock in shadow-cljs - and i want to use you example countdown timers. But I can't get it to work! How is end-time supposed to be formatted in: https://juxt.github.io/tick/#_countdown_timers `countdown-HH-mm-ss`

Full code from your site:
`(defn countdown-HH-mm-ss
  [end-time]
  (let [duration (tick/duration
                  {:tick/beginning (tick/instant)
                   :tick/end end-time})
        hours (tick/hours duration)
        minutes (tick/minutes (tick/- duration
                                      (tick/new-duration hours :hours)))
        seconds (tick/seconds (tick/- duration
                                      (tick/new-duration minutes :minutes)
                                      (tick/new-duration hours :hours)))]
    (if (tick/< (tick/instant) end-time)
      (format "%02d:%02d:%02d"
              hours minutes seconds)
      "Time's up!")))`

I have included `[tick "0.6.0"]` in my shadow-cljs.edn file and `[tick.core :as tick]` and `[goog.string :as gstring]` in my .cljs work file. I imported the goog.string so that "format" will work with `gstring/format`.

And when I check `(defprotocol ITimeSpan
  (beginning [_] "Return the beginning of a span of time")
  (end [_] "Return the end of a span of time"))` it says it should be a span of time - but not how it should be formatted. So I'm still clueless.

So when i call for example: `(countdown-HH-mm-ss 100)`  or `(countdown-HH-mm-ss "10:10:10")` or whatever I could think of it dosen't work. 

This is probably super simple - but need help! :)

**Comment by henryw374** [comment]
I think that example expects a duration as argument

**Comment by henryw374** [comment]
Pass an instant as arg

**Comment by hjer** [comment]
> Pass an instant as arg

Thanks for your reply! Can you please give me an example?

**Comment by henryw374** [comment]
have you read the docs on how to create an instant?

**Comment by hjer** [comment]
Hello! I have now! Thank you for the help! :)
