### ISSUE TITLE
missing tick/parse-long

### ISSUE THREAD

**Issue by cezarykosinski** [juxt/tick#186]
Hey guys, first of all very cool library, I use it by default now in my projects. However I stumbled on a weird problem. Isn't there really a better way to read time given in epoch seconds in tick in the other way than below? The docs didn't help me - maybe my mistake. Please point me to fn I missed.

(defn epoch->time [seconds]
  (t/>> (t/epoch) (t/new-duration seconds :seconds)))

Is this really the way I should do it? I hope not. Seems sketchy.

Issue sparked during the discussion in [clojurians slack channel](https://clojurians.slack.com/archives/C0CFGN25D/p1682702156153169).

Thanks for all the help and keep it going. 🤙

**Comment by cezarykosinski** [comment]
([c/from-long](https://github.com/clj-time/clj-time/blob/master/README.md#clj-timecoerce) 893462400000)
=> #<DateTime 1998-04-25T00:00:00.000Z>

**Comment by dvingo** [comment]
I think this should cover your use-case:
```clojure
; local date-time
(-> 893462400000 t/instant t/date-time)
 ;  => #time/date-time"1998-04-24T20:00"
 
; zoned-date-time in UTC
(-> 893462400000 t/instant (t/in "UTC"))
; => #time/zoned-date-time"1998-04-25T00:00Z[UTC]"
```
Definitely recommend reading the java.time docs and playing with the API directly in a JVM REPL.
After getting a good grasp of the API tick makes a lot more sense.
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html

**Comment by henryw374** [comment]
Hi, glad tick is helping you

cljc.java-time.instant/of-epoch-second would be the right fn for your case I think 

You're not the first to raise this kind of thing (e.g. https://github.com/juxt/tick/discussions/184), so I just updated the `contributing` info:

```
java.time has a much larger API than tick. tick only aims to cover what we feel are the most commonly occurring date-time use-cases. At this point (5+ years into the life of tick) we don't feel we are missing any functions, but if you feel you have a good candidate for addition, please argue why you think it is an everyday need as part of the issue. 

Where tick doesn't provide the api you need,
you can look at the java.time api (most readily available as https://github.com/henryw374/cljc.java-time[cljc.java-time]) to see if there alternatives.
```

pls reopen if needed

**Comment by dvingo** [comment]
Calling `t/instant` with a number invokes `cljc.java-time.instant/of-epoch-milli` so you can multiply seconds by 1000 and use that as well
https://github.com/juxt/tick/blob/b0b33558363a4c92956638377391891e43885224/src/tick/core.cljc#L223

**Comment by cezarykosinski** [comment]
Thanks all. I got it now. It's just different interface, but and functionality the same. Nothing lacking there indeed.
