### ISSUE TITLE
create cheatsheet

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#187]
possible content:

# Naming (compared to java.time)

LocalDate => date
LocalDateTime => date-time

java.util.Date => inst 
js/Date => inst

otherwise the same as java.time

# Dates and Times

### Now 

(t/date), (t/zoned-date-time), (t/instant)

temporarily change what clock is used to get the `now` or `where` information with `with-clock`

(t/with-clock (t/instant "2023-08-23T15:49:21.941342Z") 
   (t/date))

### Extraction 

(t/date (t/zoned-date-time))

(t/truncate (t/instant) :hours) 

### Combining parts

(-> (t/date)
    (t/at "00:00")
    (t/in "UTC"))

(-> (t/time "10:10")
    (t/on (t/date)))

### from/to Strings 

(t/parse-... "xxx", (t/formatter "pattern"))

(t/format (t/date) (t/formatter "pattern"))

### from parts 

new-... 

for example

new-date
new-time

### Relative 

<<, >>

for example `(t/>> (t/instant) (t/new-duration 1 :days))`

# Amounts of Time

### From Units 

(t/new-duration 5 :minutes)

(t/new-period 1 :months)

### From points in time

(t/between foo far)

## Arithmetic

+/-

(t/+ (t/new-duration 5 :minutes) (t/new-duration 5 :minutes) (t/new-duration 5 :minutes))

## Extract parts

millis, hours 

# Comparison

<, <=, =, ...

max, max-by, min, min-by

# Predicates 

(t/date-time? x)

# Units

t/APRIL,
t/DECEMBER ...

t/FRIDAY, t/MONDAY...

other things to put somewhere...

millis
millisecond
of-minutes
unit-map, units

**Comment by dvingo** [comment]
A cheatsheet would be a great idea!

I recently learned about day.js which is used by antd cmponents.

The API docs on their site has a nice conceptual grouping of the functionality:
https://day.js.org/docs/en/parse/parse
perhaps this can be an inspiration for the cheatsheet.
