### ISSUE TITLE
weekday in case fails

### ISSUE THREAD

**Issue by awb99** [juxt/tick#191]
I wrote a function that gets the next day, which avoids weekends (satursday/sunday).
I tried implementing it with "case weekday" (see function below), but this would not work.
Using cond works. I guess there is just some sort of clojure interface that is missing, why
using case would not work.

```
(def day (t/new-duration 1 :days))
(def days2 (t/new-duration 2 :days))
(def days3 (t/new-duration 3 :days))

(defn next-date [dt-current]
   (let [weekday (t/day-of-week dt-current)]
     (t/>> dt-current
        (cond ; case does not work
          (= t/FRIDAY weekday) days3
          (= t/SATURDAY weekday) days2
          :else  day))))
```

**Comment by henryw374** [comment]
Case only works with compile time literals https://clojuredocs.org/clojure.core/case
