### ISSUE TITLE
api for creating specs

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#20]
specs for all the java.time domain types and intervals

fns to create generators for these, along the lines of clojure.spec/inst-in

not really thought about coercion yet

**Comment by henryw374** [comment]
started on https://github.com/henryw374/time-specs

**Comment by maxthoursie** [comment]
I would really like having the type predicate functions being part of the main api.

Thank you for your work!

**Comment by henryw374** [comment]
pred fns now in `cljc.java-time.extn.predicates` thanks to @joda . 0.4.21-alpha has this

**Comment by henryw374** [comment]
maybe resurrect this if spec 2 moves along
