### ISSUE TITLE
always return boolean from comparators:  >,<,>= 

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#24]
at the moment it is bool in some cases, truthy/falsy in others

**Comment by malcolmsparks** [comment]
Agreed. Comparators should always return booleans.

**Comment by henryw374** [comment]
related point: ITimeComparison is extended to LocalDate etc in core.cljc and in interval.cljc, so core one can go

**Comment by malcolmsparks** [comment]
The interval ones are the problem here, since interval will always be required after core.
