### ISSUE TITLE
Support singular duration terminology.

### ISSUE THREAD

**Issue by SevereOverfl0w** [juxt/tick#28]
`(t/new-duration 1 :minute)` doesn't work, given the interface, it feels like it should. Minor semantic thing.

**Comment by henryw374** [comment]
in java.time (and ECMA Temporal) singular terminology is always for fields of a Temporal (date thing), e.g. `date.getMinute()` and plural is always for fields of a TemporalAmount (period, duration). Tick maintains that, so you can know when to use `t/minute` vs `t/minutes`. 

I worry this change might cause confusion on something already pretty subtle. feel free to reopen with more discussion.
