### ISSUE TITLE
No result when scheduled function has wrong arity

### ISSUE THREAD

**Issue by amoe** [juxt/tick#3]
Hi there, I wondered what should the behaviour be when I try to schedule a function with the wrong arity?  It becomes clear reasonably quickly that functions that are the first argument to `schedule/schedule` should take one argument, being the specific tick of the clock that triggered the call.  But if I pass a zero argument function, nothing happens at all, not even any side-effects, indicating that the function never gets called.  I presume some ArityException happens internally, but I never see it.

I'm not sure if there should be an error message from `tick` in this case, or maybe the user can use one of Clojure/Java's existing mechanisms to report these errors.

**Comment by malcolmsparks** [comment]
Very good point. The async nature of scheduling poses the problem of where to put errors. I think an error-handler could be specified on the schedule which will get called with any captured errors.

**Comment by sooheon** [comment]
In the meantime, would it make sense to use `spec/fspec` to specify that the first arg to `schedule/schedule` is a function that takes just one argument?

**Comment by martinklepsch** [comment]
I also just bumped into this, weirdly it also doesn't show up when you set an [uncaught exception handler](https://stuartsierra.com/2015/05/27/clojure-uncaught-exceptions). Quite confusing. For the time being noting it in the README would be a good idea. Maybe later add a `println` for failures or some logging?

**Comment by kenfehling** [comment]
@martinklepsch Are you able to get any errors from inside a scheduled function when using the uncaught exception handler? I'm trying right now but nothing seems to get through.

**Comment by martinklepsch** [comment]
Nothing shows up even with the uncaught exception handler.

**Comment by malcolmsparks** [comment]
I think tick is prone to this issue from https://stuartsierra.com/2015/05/27/clojure-uncaught-exceptions 

> Another wrinkle: exceptions inside a future are always caught by the Future. The exception will not be thrown until something calls Future.get (deref in Clojure).

Need investigation and fixing, certainly.

**Comment by martinklepsch** [comment]
```diff
diff --git a/src/tick/schedule.clj b/src/tick/schedule.clj
index d280dae..6e362f1 100644
--- a/src/tick/schedule.clj
+++ b/src/tick/schedule.clj
@@ -94,7 +94,12 @@
    (schedule trigger timeline {}))
   ([trigger timeline {:keys [executor]}]
    (map->SchedulingTicker
-    {:trigger trigger
+    {:trigger (fn trigger-run-wrap [dt]
+                (try
+                  (trigger dt)
+                  (catch Throwable t
+                    (println "ERROR Exception in scheduled function:" (.getMessage t))
+                    (println "Wrap your scheduled function in a try/catch to customize error handling"))))
      :timeline timeline
      :state (atom {})
      :executor (or executor (new ScheduledThreadPoolExecutor 16))
```

I think this would be a great improvement already but I'm not so happy with the `println` call as it is hard to capture STDOUT from different threads in tests (afaik). To fix it we'd need to introduce something like `clojure.tools.logging` but that would mean introducing a new dependency.

Any other alternatives I'm missing?

**Comment by kenfehling** [comment]
Hmm, interesting. Could it be `(.printStackTrace t)` instead of `println`?

**Comment by martinklepsch** [comment]
@kenfehling yes, that's way better than `println`. The issue of testing it remains though? Do you have any ideas for how we could test that the message is printed?

**Comment by malcolmsparks** [comment]
I think it would be helpful to be able to register an `:error-handler` on the scheduler that would be passed all errors. The user code could decide what to do with the error and perhaps return an `:abort` or `:continue` keyword as a return value. What do you think?

**Comment by martinklepsch** [comment]
@malcolmsparks the error handler option sounds good, probably better than passing a reference to the executor.

What do you imagine would the default be? I think the current default is pretty hostile and needs to change. So my vote goes to: catch, log, continue or abort. Aborting isn't too nice of an experience but forces users to think about these errors relatively early so it's a trade-off between ease of use and "forced education".

**Comment by malcolmsparks** [comment]
I feel the default should be to continue (fail-fast is nice, but it's hard to explain its merits to managers angry at your batch jobs not running all night). I think the default error handling should be to print and printStackTrace. I think `*out*` is bound to the threads in the pool, if not perhaps it should be.

**Comment by kenfehling** [comment]
The [at-at](https://github.com/overtone/at-at) library has the same issue with exceptions but somebody forked it and got them working.
Here's the fork's comparison: https://github.com/overtone/at-at/compare/master...silasdavis:silasdavis

Maybe this would be helpful or inspire some ideas, particularly this commit:
https://github.com/overtone/at-at/commit/634fc4d59535b7c5ea67a7e2a8ca4133e05cfdb4

**Comment by malcolmsparks** [comment]
I've been working on this earlier today. I have most of the error-handler functionality working, with `:abort` and `:continue`. It has turned out to be quite tricky to implement the `:abort` fail-fast behaviour but doable. I think it's a nice feature. 

One thing that it has opened up is the question of whether a triggered function might have some ability to influence the scheduler - for example, telling it to abort, or updating the remaining timeline.

**Comment by martinklepsch** [comment]
Hey @malcolmsparks, also started working on this and then got overwhelmed by `callback` and also a little sidetracked by other stuff :) I'm not sure how useful they will be but [here are the changes I've made](https://gist.github.com/martinklepsch/befb8033ef4a1ea7812c0815f19b6d71).

> One thing that it has opened up is the question of whether a triggered function might have some ability to influence the scheduler - for example, telling it to abort, or updating the remaining timeline.

The ability to update the timeline implies the ability to abort, right? I think that might be worth consideration although I'm not sure what it really brings to the table. I think at this point it's probably best to chose the most flexible solution in terms of "API evolution" — whatever that may be.

**Comment by malcolmsparks** [comment]
The design of the scheduler means that each callback is responsible for scheduling the next callback, so it's possible that a given callback can influence the rest of the timeline and subsequent callbacks. It's an interesting (and possibly useful) feature to consider. Abort is really a particular case of the more general update of the remaining timeline: `(remove some?)`

**Comment by malcolmsparks** [comment]
See branch for my error-handling code: https://github.com/juxt/tick/tree/error-handler

**Comment by martinklepsch** [comment]
Unrelated to this feature mostly but, I'm wondering if the `callback` should just get the ticker as argument? It basically gets all fields as separate args making the argvec somewhat complex.

**Comment by malcolmsparks** [comment]
Yep - the code has just evolved that way and needs refactoring ;)

**Comment by ikzk** [comment]
Any update?

**Comment by henryw374** [comment]
Scheduling has been removed from tick now. Chime lib might have what you need.
