### ISSUE TITLE
Transit Encoding

### ISSUE THREAD

**Issue by currentoor** [juxt/tick#34]
First off, thank you for the fantastic library!

Since we have literals for the various values, it can be handy to encode/decode them in transit+json. Then you can communicate them between client and server.

I defined and installed these handlers for `LocalDate` and verified they worked with sente.
```clj
#?(:cljs
   (deftype LocalDateHandler []
     Object
     (tag [_ _] "time/date")
     (rep [_ r] (str r))
     (stringRep [_ _] nil)))

#?(:clj
   (deftype LocalDateHandler []
     com.cognitect.transit.WriteHandler
     (tag [_ _] "time/date")
     (rep [_ r] (str r))
     (stringRep [_ r] (str r))
     (getVerboseHandler [_] nil)))
```

Does it make sense to have a namespace for transit handlers like these? I figured other people might want this also.

**Comment by henryw374** [comment]
Hi. Glad you're liking it ;-)

This sounds good. I think it'd go in https://github.com/henryw374/time-literals, which tick depends on. Would welcome a PR there.

**Comment by currentoor** [comment]
Agreed :-)

**Comment by jdf-id-au** [comment]
Excuse the crossposting but [here's a sketch](https://gist.github.com/jdf-id-au/2e91fb63ce396b722c1d6770154f1815) of what it might look like.
