### ISSUE TITLE
A few errors using Tick on ClojureScript with Piggieback/NodeJS

### ISSUE THREAD

**Issue by alzadude** [juxt/tick#35]
Hi there,

I'm evaluating Tick (version `0.4.14-alpha`) and I'm seeing a few errors on ClojureScript with Piggieback/NodeJS..

Could anyone help me out? Thanks!

```
(require '[tick.alpha.api :as t])
(require '[tick.timezone])

; works
(t/truncate (t/instant 1552786820310) :seconds)

; works
(t/format (t/truncate (t/instant 1552786820310) :seconds))

; error
(t/format :iso-instant (t/truncate (t/instant 1552786820310) :seconds))
; Execution error (RangeError) at (<cljs repl>:1) .
; Maximum call stack size exceeded

; error
(t/format :iso-zoned-date-time (t/truncate (t/instant 1552786820310) :seconds))
; Execution error (RangeError) at (<cljs repl>:1) .
; Maximum call stack size exceeded

; error
(t/in (t/truncate (t/instant 1552786820310) :seconds) "Europe/London")
; Execution error (Error) at (<cljs repl>:1) .
; unsupported ZoneId:Europe/London

; error
(t/in (t/truncate (t/instant 1552786820310) :seconds) (t/zone "Europe/London"))
; Execution error (Error) at (<cljs repl>:1) .
; unsupported ZoneId:Europe/London
```

**Comment by henryw374** [comment]
Hi,

I've run through the above with 0.4.14-alpha in both node and browser environments and the only one which doesn't work is 

`(t/format :iso-zoned-date-time (t/truncate (t/instant 1552786820310) :seconds))`

which fails with `Unsupported field: Year` as expected.

The fact that your getting unsupported zone tells me the zone data is not getting loaded. If you can create a repro project I'll have a look at that.

**Comment by alzadude** [comment]
> Hi,
> I've run through the above with 0.4.14-alpha in both node and browser environments and the only one which doesn't work is
> (t/format :iso-zoned-date-time (t/truncate (t/instant 1552786820310) :seconds))
> which fails with Unsupported field: Year as expected.
> The fact that your getting unsupported zone tells me the zone data is not getting loaded. If you can create a repro project I'll have a look at that.

Hi, thanks for looking into this!

I've created a repro project here: https://github.com/alzadude/tick-issue

I'm getting the errors (and empty timezones) in my dev environment (Calva in VSCode on Windows/WSL), and also in a plain cljs repl started using `clj -m cljs.main -re node`

Clojure version: 1.10.0.411
Node version: 10.14.1
Environment:  WSL (Debian Stretch) on Windows 10

Thanks 🙂

**Comment by henryw374** [comment]
So the issue comes down to how the underlying npm libraries are consumed. 

Currently they are provided via cljsjs to make things easy for what I think are the majority. Here is a workaround which is similar to the one for shadow cljs, mentioned here: https://juxt.pro/tick/docs/index.html#_clojurescript 

I have created a fork of your repo, https://github.com/henryw374/tick-issue which:

 - excludes the cljsjs deps and contains shims instead. 
 - New ns `node-repl` for start a node process where the cljs compiler opts to get the dependencies from npm directly
 - in your 'tick ns the shims are required which do npm requires 

.... then all your examples work as expected. 

So we still need a proper solution here to make things easier  ... to be continued...

**Comment by henryw374** [comment]
checking in with an update ... I've been discussing the problem https://github.com/clojure/clojurescript-site/issues/320

**Comment by henryw374** [comment]
Ok, if you depend on tick sha 8946768ccd4c0354063ed2f9d49230a562fa3f47 then the described problems are fixed. We'll do a clojars release with that soon.

The fix has been to update the script of the js-joda foreign-lib to only run and assign the JSJoda global if it is not already present. 

I've added a bit about alternative ways of consuming the npm dependencies in the docs: https://github.com/juxt/tick/blob/master/docs/cljs.adoc

**Comment by alzadude** [comment]
Hi @henryw374,

Apologies for the delay in responding.. I've managed to get this working in the example project, based on what I saw in your fork. I am using version 0.4.19-alpha.

I must admit my ClojureScript/Node interop knowledge is not great, I got a bit lost re: cljsjs/shims/foreign-libs etc.

My solution in the example project uses `package.json` and `npm install`, since I'm familiar with that and appears to be working for what I need 🙂

https://github.com/alzadude/tick-issue/

However, after resolving the timezone part, unfortunately I hit another issue concerning formatting 😕

I have added a different example to the project for that:

https://github.com/alzadude/tick-issue/blob/master/src/tick_format.cljc
```
(ns tick-format
  (:require
   #?(:cljs [cljsjs.js-joda])
   #?(:cljs [cljsjs.js-joda-timezone])
   #?(:cljs [cljsjs.js-joda-locale-en-us])
   [tick.alpha.api :as t]
   [tick.format :as tf]
   [tick.locale-en-us]
   [tick.timezone]))

; ok
(def inst (t/truncate (t/instant 1561224025879) :seconds))

; ok
(t/format :iso-local-date (t/in inst "UTC"))

; #object[Error Error: Locale is nil, try adding a require '[tick.locale-en-us]]
(t/format (tf/formatter "yyyy/M/d") (t/in inst "UTC"))

; suspected cause: tick.format/formatter, line 43
; this expr needs to return an object, rather than throw an error!
(goog.object/get js/JSJodaLocale "Locale")
```
As you can see, the error message suggests to add `tick.locale-en-us` to the requires, but I have already done that. I had a quick look at the tick source code, and based on the error message it looks like `tick.format/formatter`, line 43 might be related.

Is this issue related to the earlier issue somehow, and could also be resolved with a shim?

Thanks!

**Comment by alzadude** [comment]
> 
> Is this issue related to the earlier issue somehow, and could also be resolved with a shim?
> 

Hi @henryw374,

Quick update: I managed to fix the formatting issue, turns out the locale shim had the wrong import and wasn't setting the correct JS global. I've fixed that in my example project, and everything I need is working as expected now. Please see the latest code:

https://github.com/alzadude/tick-issue/

Thanks!
