### ISSUE TITLE
(seconds 60) errors out -- don't know how to make a Duration from a Long?

### ISSUE THREAD

**Issue by lvh** [juxt/tick#36]
`(seconds 60)` with `tick {:mvn/version "0.4.14-alpha"}` throws:

```
java.lang.IllegalArgumentException
   No implementation of method: :seconds of protocol: #'tick.core/ITimeLength
   found for class: java.lang.Long
```

**Comment by henryw374** [comment]
`(t/new-duration 60 :seconds)` is what you're after. 

If you were following this bit of the docs, it's out of date unfortunately. we'll update
http://juxt.pro/tick/docs/index.html#_durations_periods

**Comment by lvh** [comment]
Thanks!
