### ISSUE TITLE
Create a period from an interval?

### ISSUE THREAD

**Issue by polvoblanco** [juxt/tick#37]
Hi,

Is there a way to create a period from an interval?

If you, for example, want to find out how many months or years there are between two dates, you can't call years or months on the interval as there doesn't seem to be any way to create a period like you can a duration for days, hours, minutes etc.

Thanks

**Comment by henryw374** [comment]
Hi, I'm not totally sure about what you mean when you say 'create a period like you can a duration for days, hours, minutes etc.' - is there a way to create a duration from an interval with tick? but anyway.. here's what I think may help...

Dropping to java.time you can create durations with `(cljc.java-time.duration/between (t/date-time) (t/date-time))`

where the args come from `(t/beginning my-interval)`  `(t/end my-interval)`

To create a period, first truncate the interval beginning and end to local dates :`(t/date xx)`, then use
`cljc.java-time.period/between`. and/or anything else from java.time https://www.baeldung.com/java-date-difference via fns in cljc.java-time

**Comment by polvoblanco** [comment]
Hi, thanks for that, what I was trying to do is create a function where I could pass in two dates and a period (minutes, hours, days, weeks, months, years) and get back the count between the two dates.  This was easy for minutes, hours, days and weeks as tick provided `t/duration` to create a duration between two dates on which I could then call `t/minutes`, `t/hours`, `t/days`.  However as soon as you try and call `t/months` or `t/years` it would fail as they require a period not a duration (tick doesn't provide a `t/period` method).  Dropping to java-time and using `cljc.java-time.period/between` to get the period has fixed this so I can now call `t/years` and `clic.java-time.period/to-total-months`.

Many thanks.

**Comment by henryw374** [comment]
great
