### ISSUE TITLE
How to get ordinal values for week days?

### ISSUE THREAD

**Issue by esp1** [juxt/tick#40]
First of all, thanks for creating `tick`! This is the most sensible and powerful time API I've come across - I'm really enjoying using it.

One thing I noticed is there doesn't seem to be a way to get ordinal values for week days. The `t/day-of-week` function returns def'ed constant values like `#time/day-of-week "MONDAY"`, which is nice, but sometimes it is useful to get their ordinal values as well. For example, I was trying to find the beginning and end of the week period surrounding a given date. To do this, I needed to find the distance from the current date to the preceding Sunday and to the following Saturday.

The `t/int` function works to translate similar named month constants to ordinal values, but it does not work for the day of week constants:
```
=> (t/int t/JULY)
7

=> (t/int t/MONDAY)
Execution error (ClassCastException) at tick.core/eval43746$fn (core.cljc:250).
class java.time.DayOfWeek cannot be cast to class java.lang.Character (java.time.DayOfWeek and java.lang.Character are in module java.base of loader 'bootstrap')
class java.lang.ClassCastException
```

**Comment by esp1** [comment]
Ah, I see now that the day of week value is a `java.time.DayOfWeek` instance, and I can get the value via e.g. `(.getValue t/MONDAY)`. It still may be nice to have `t/int` provide this value instead of having to resort to interop.

**Comment by henryw374** [comment]
thanks for reporting. PR welcome
