### ISSUE TITLE
How to use other locale rather that en-us?

### ISSUE THREAD

**Issue by DogLooksGood** [juxt/tick#48]
I found `tick.format/format` needs a locale.

I want to use `@js-joda/locale_zh`, is there any support in tick to use another locale?

**Comment by henryw374** [comment]
Hi. So firstly load the js. If you're on shadow it's just an ns require, or
create a foreign lib if not.

Then, take a look at tick.format ns... I think the formatter is an extra
argument to the format function.

That's it!

Hopefully that's all clear?

**Comment by DogLooksGood** [comment]
That's make sense, thanks!
