### ISSUE TITLE
date-time -> inst conversion doesn't respect clock

### ISSUE THREAD

**Issue by maxthoursie** [juxt/tick#49]
Converting a date-time to a inst doesn't respect a clock binding. It uses the system default zone instead.

```clojure
(t/with-clock (t/in (t/clock) "Pacific/Honolulu")
 (-> (t/date-time "2019-08-07T12:00") (t/inst)))
=> #inst"2019-08-07T10:00:00.000-00:00"
```
The expected answer is 22:00
```clojure
(-> (t/zoned-date-time "2019-08-07T12:00-10:00[Pacific/Honolulu]") (t/inst))
=> #inst"2019-08-07T22:00:00.000-00:00"
```

The reverse conversion does respect the clock
```clojure
(t/with-clock (t/in (t/clock) "Pacific/Honolulu")
              (t/zoned-date-time #inst"2019-08-07T22:00"))
=> #time/zoned-date-time"2019-08-07T12:00-10:00[Pacific/Honolulu]"
```

If you agree this is an error I'd be happy to provide a patch.

**Comment by malcolmsparks** [comment]
Yes, this does look like an error - I'd like to see the patch if it's fairly easy to make and discuss with @henryw374

**Comment by henryw374** [comment]
Thanks for the patch. Now merged in.
