### ISSUE TITLE
Conversion of integer/long to instant CLJS Error

### ISSUE THREAD

**Issue by eskemojoe007** [juxt/tick#57]
Within the documentation it says the following two lines are valid:
```clojure
(require '[tick.alpha.api :as t])
(t/instant (t/new-duration 1531468976048 :millis))
(t/inst (t/new-duration 1531468976 :seconds))
```
When runing within clojure this works great and results in the proper output of `2018-07-13T08:02:56.048Z`

Within my clojurescript repl however It does not work with the following error:
```
#object[Error Error: No protocol method IConversion.instant defined for type object: PT425408H2M56.048S]
   cljs.core/missing-protocol (jar:file:/home/david/.m2/repository/org/clojure/clojurescript/1.10.520/clojurescript-1.10.520.jar!/cljs/core.cljs:316:4)
   tick.core/instant (jar:file:/home/david/.m2/repository/tick/tick/0.4.17-alpha/tick-0.4.17-alpha.jar!/tick/core.cljc:146:1)
   tick.alpha.api.instant.cljs$core$IFn$_invoke$arity$1 (jar:file:/home/david/.m2/repository/tick/tick/0.4.17-alpha/tick-0.4.17-alpha.jar!/tick/alpha/api.cljc:73:9)
   tick$alpha$api$instant (jar:file:/home/david/.m2/repository/tick/tick/0.4.17-alpha/tick-0.4.17-alpha.jar!/tick/alpha/api.cljc:71:1)
```

I would expect it to work within both worlds.

**Comment by henryw374** [comment]
Hi, that is fixed on master, if you can depend on that?

Probably we should set up a snapshot clojars build

**Comment by eskemojoe007** [comment]
Yeah...I've upgraded to 0.4.19-alpha with the same issue.  I'll try to install from the master branch, I've just always used the clojars with lein to get all my packages.

**Comment by henryw374** [comment]
0.4.20-alpha now released
