### ISSUE TITLE
tick.interval/complement fails on meeting intervals

### ISSUE THREAD

**Issue by jjttjj** [juxt/tick#58]
If the `coll` passed to `tick.interval/complement` contains any two intervals that `meet?`, it will attempt to create an interval with the beginning after the end and throw an exception:
```
(tick.interval/complement [(t/yesterday) (t/today)])
;;Exception: Interval must span between two times, the first must be before the second
```
I believed this could be fixed by changing the following lines here:
https://github.com/juxt/tick/blob/e777e93ca80c19bc2b9f4bea76d096f037afe510/src/tick/interval.cljc#L666-L667

To
```clojure
...
(let [r (->> coll
             (partition 2 1)
             (remove (fn [[x y]] (meets? x y))) ;;alternatively, clojure.core/keep could replace map
             (map (fn [[x y]] (new-interval (t/end x) (t/beginning y)))))]
...
```
If you are interested I can provide a PR with tests.

Edit:
To expand on this a little bit, it's unclear what the argument passed to `complement` should be, but it seems like mostly likely it should be an ordered disjoint interval sequence, which should allow for intervals which `meet`, as described above.

**Comment by malcolmsparks** [comment]
Yes please, a PR would be most welcome
