### ISSUE TITLE
Extending API to Instant

### ISSUE THREAD

**Issue by currentoor** [juxt/tick#65]
I'm using this project with Datomic, which can only store `java.time.Date` values natively. So I do this sort of thing all the time.
```clj 
(t/inst (t/+ (t/instant #inst "...") (t/new-duration 10 :minutes))) => #inst "..."
```

Would you be interested in a PR that extends the API to do this conversion internally for inst's? So then we can just do this
```clj
(t/+ #inst "..." (t/new-duration 10 :minutes)) => #inst "..."
```

**Comment by currentoor** [comment]
@henryw374 mentioning you just in case you don't see this.

**Comment by henryw374** [comment]
Hi.

This would work for you in current version:

`(t/>> (java.util.Date.) (t/new-duration 10 :minutes))`


 I'm in 2 minds about ITimeShift and ITimeArithmetic generally. There's overlap between them and ITimeShift doesn't seem quite right to me.

**Comment by currentoor** [comment]
Oh ok, wonderful I'll just use that then. Thanks! 👍

**Comment by awb99** [comment]
I notice a bug in the latest tick verion. The type changes when I run tick/>>. So I have to cast to t/inst:
```
(-> (t/>> (t/inst) (t/new-duration 30 :days))      t/inst)
```

**Comment by henryw374** [comment]
ok weird. I can't see how that worked before.
