### ISSUE TITLE
Bring tick.deprecated.schedule back from the dead?

### ISSUE THREAD

**Issue by MageMasher** [juxt/tick#66]
Hi friends, I'm in need of a scheduler and believe the two `ITicker` implementations in `tick.deprecated.schedule` are close to what I need from an API and functionality perspective. If I were to work on them, would there be a desire to bring them back from `deprecated` status or should I make my own scheduler library inspired by them that builds on top of the current `tick` public api?

**Comment by henryw374** [comment]
Hi. Thanks for the interest. we will not be reviving the scheduling. Chime lib might have what you need.
