### ISSUE TITLE
Define a print-method for AtomicClock

### ISSUE THREAD

**Issue by danielcompton** [juxt/tick#69]
I get the following error when trying to print an AtomicClock

```clojure
(tick/atom (tick/clock (Instant/now)))

Error printing return value (IllegalArgumentException) at clojure.lang.MultiFn/findAndCacheBestMethod (MultiFn.java:179).
Multiple methods in multimethod 'print-method' match dispatch value: class tick.core.AtomicClock -> interface clojure.lang.IDeref and interface clojure.lang.IRecord, and neither is preferred
```

You can see one possible resolution of this kind of issue here: https://gist.github.com/rwilson/34c88a97c6260a7dc703 (though note that in that case they are working with pprint).

It would probably be good to define `print-method` for the AtomicClock, though I'm not really sure what the expected printing should be? For the meantime, I've used this:

```clojure
(let [meth (get-method print-method IDeref)]
  (defmethod print-method AtomicClock [v writer]
    (meth v writer)))

(tick/atom (tick/clock (Instant/now)))
=> #object[tick.core.AtomicClock 0x6ec9db72 {:status :ready, :val #time/instant"2019-12-01T18:53:30.744363Z"}]
```

It looks like work on this was started, but it might need to add a preference for IRecord?

https://github.com/juxt/tick/blob/4241aaa4ba3860a8d0126ffa5a2baa93279f7e0d/src/tick/core.cljc#L724-L729

**Comment by henryw374** [comment]
think this one is fixed now by https://github.com/juxt/tick/pull/90/files?
