### ISSUE TITLE
schedule/start does not skip times in the past

### ISSUE THREAD

**Issue by terjesb** [juxt/tick#7]
The schedule examples typically start from just-now times or future times.
I did a quick test to see what would happen if I wanted to use tick for cron-like scheduling as an alternative to immutant.scheduling, which currently isn’t timezone-aware.
However, it appears that tick’s scheduler also fires for times in the past.
I expected these to be ignored, or is there a use case for scheduling times in the past?

(Haven't yet tested what resume does.)

```
(def tl  (tick.timeline/timeline (tick.timeline/periodic-seq
  (.. (java-time/local-date "2017-08-17") (atTime 9 41) (atZone (java-time/zone-id "Europe/Oslo")))
  (hours 1))))

(def sch (tick.schedule/schedule println tl))

;; this rapidly fires 6 ticks, expected 0
(tick.schedule/start sch (tick.clock/fixed-clock (java-time/zoned-date-time 2017 8 17 15 30)))

```

**Comment by malcolmsparks** [comment]
That's the intended behaviour. The rationale is that a scheduler may have been paused and so the policy is that all times on the timeline that lie before the clock are triggered. If you want to avoid, construct a timeline with the past times removed. (This will be easier in tick in a future release where there will be more operators on timelines).

**Comment by terjesb** [comment]
Thanks, and fair enough.

I can understand that a generic scheduler might want the current behavior (potentially getting many ticks in parallell "at the same time"), and that my question was perhaps specific to a job scheduler scenario. I was thinking about putting the task as the scheduled function, but for a job scheduler it might make more sense for that function to just put the ticks on a channel, and then also be able to remove times before just-now and control number of parallell consumers when reading from the channel. That way tick is only concerned with the ticking.
