### ISSUE TITLE
Extend IConversion to AtomicClock?

### ISSUE THREAD

**Issue by danielcompton** [juxt/tick#71]
I think it makes sense for the AtomicClock record to implement the IConversion protocol. It is already extended to `Clock`, I think it should be on AtomicClock too? My workaround for now:

```clojure
(extend-type AtomicClock
  tick/IConversion
  (inst [this] (tick/inst (.instant (tick/clock this))))
  (instant [this] (tick/instant (.instant (tick/clock this)))) ;; slightly redundant, but keeps with the pattern
  (offset-date-time [this] (tick/offset-date-time (.instant (tick/clock this))))
  (zoned-date-time [this] (tick/zoned-date-time (.instant (tick/clock this)))))
```

**Comment by malcolmsparks** [comment]
For all of these cases, can you not just deref the atomic clock?

Examples:

```clojure
(t/instant @(t/atom (t/clock "2020-10-22T10:00:00Z")))
```
```clojure
(t/zoned-date-time @(t/atom))
```

I think we'll close this issue for now, but feel free to respond if you want to make a case for this.
