### ISSUE TITLE
Why ZonedDateTime and not Instant

### ISSUE THREAD

**Issue by martinklepsch** [juxt/tick#8]
I just tried creating a timeline with an `Instant` as starting point. The timeline was created without error but the scheduled function never ran. Reading the docs I noticed that it says `ZonedDateTime`. 

Is there something wrong in creating timelines with an `Instant` as starting point?
Is that something that `tick` should potentially be able to do?

**Comment by malcolmsparks** [comment]
I agree. It should do that. Needs fixing. Let's chat about it next week at ClojuTRE?

**Comment by martinklepsch** [comment]
Sounds good 👍

**Comment by vincent-dm** [comment]
Any news on this?

**Comment by malcolmsparks** [comment]
Tick is in the middle of an overhaul, see master for current status. Once the API is stable, the older scheduling functionality will be re-written to use it. Both Instants and ZonedDateTime instances will be supported (I fully expect)

**Comment by henryw374** [comment]
Scheduling has been removed from tick now. Chime lib might have what you need.
