### ISSUE TITLE
range on LocalDate assumes step is in days

### ISSUE THREAD

**Issue by SevereOverfl0w** [juxt/tick#84]
This prevents something like `(t/range some-date some-other-date (t/new-duration 1 :weeks))` for a weekly breakdown.

**Comment by SevereOverfl0w** [comment]
ZonedDateTime does *not* have this behaviour.

**Comment by damionjunk** [comment]
Commenting because I ran into this as well. It looks like maybe a typo / copy-paste error, since LocalDate supports a call to .plus for a TemporalAdjustment like the other java.time classes.

**Comment by henryw374** [comment]
Looks like this was fixed a while back. See merge above
