### ISSUE TITLE
make tick work on babashka

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#86]
an initial play reveals:

no clojure.spec.  tick isn't really using that much. could easily change from spec asserts to something else

no TemporalAdjusters class. may be others. PR to babashka

not sure if time literals would work. may need to elide somehow

in the meantime, [cljc.java-time](http://widdindustries.com/tick-with-shadow-just-works/) works already

**Comment by borkdude** [comment]
@henryw374 

If you're looking to support data readers, you can `(set! *data-readers ...)` in babashka to make them work. They aren't picked up from `data_readers.clj` at this moment.

Missing java.time classes: PR welcome.

About clojure.spec: you might be able to leverage https://github.com/borkdude/spartan.spec and reader conditionals (babashka supports `:bb`). Although I think in general it's nice if libraries make spec an optional dependency (especially regarding clojure.test.check). If you want to have the specs loaded, a user can require a specific namespace maybe.

**Comment by henryw374** [comment]
@borkdude cool, thanks for the info

**Comment by henryw374** [comment]
the java.time classes already available in bb are here: https://github.com/borkdude/babashka/blob/master/src/babashka/impl/classes.clj 

tick may or may not need others

Regardless, it'd be handy to produce a diff of what's missing, and see how much of an increase it would be to have them all.

**Comment by henryw374** [comment]
I've not worked on this for a while, so before I forget it all...

there is a branch https://github.com/juxt/tick/tree/babashka which has the latest.

there is a deftype or two in tick which won't work with babashka so we'd need alternative impl of some sort. no other blockers I know of.

FYI my new plan is for https://github.com/henryw374/tempo to work on babashka from the first release - then get tick implemented on that later.

**Comment by dvingo** [comment]
I took a look at what is missing to get bb support based on your branch, Henry, and have all the tests in the tick core api tests passing except one on this branch
https://github.com/dvingo/tick/tree/babashka-update
which is commented out for `:bb`- the `java.util.Locale` doesn't seem to have any effect.

I added the missing java classes to bb here:
https://github.com/babashka/babashka/pull/1490

**Comment by borkdude** [comment]
bb 1.2.174 is out now

**Comment by henryw374** [comment]
0.6.0 released with bb support. Thanks @dvingo and @borkdude !
