### ISSUE TITLE
Stopping should cancel any running jobs

### ISSUE THREAD

**Issue by martinklepsch** [juxt/tick#9]
```clojure
(let [tl (tick.timeline/timeline
          (tick.timeline/periodic-seq
           (tick.clock/now)
           (tick.core/minutes 1)))
      job-fn (fn [tick]
               (doseq [idx (range 15)]
                 (println idx tick)
                 (Thread/sleep 1000)))]
  (def sched (tick.schedule/schedule job-fn tl))
  (tick.schedule/start sched (tick.clock/clock-ticking-in-seconds)))

(tick.schedule/stop sched)
```
If you evaluate the `let` and then stop the schedule you will still see the remaining `println` calls of the initial call to `job-fn`. I think these probably should get cancelled as well.

**Comment by malcolmsparks** [comment]
Thanks. Looks like a bug, maybe introduced by my last commit.

**Comment by kwladyka** [comment]
I can't agree `stop` should cancel running jobs. Jobs should finish the job if started. The process shouldn't be interrupted. Eventually some kind of soft kill signal can be send.

**Comment by malcolmsparks** [comment]
I agree with @kwladyka  - you can achieve the cancellation of running jobs by calling `shutdownNow` on the executor. You can provide your own executor in the second form of `tick.schedule/schedule`.
