### ISSUE TITLE
The duration expressions in the examples of clock shift operations does not work in the document

### ISSUE THREAD

**Issue by yubrshen** [juxt/tick#92]
In the document of https://github.com/juxt/tick/blob/master/docs/clocks.adoc

`(<< (clock) (hours 2))` would fail with `(hours 2)` of error:
```
No implementation of method: :hours of protocol: #'tick.core/ITimeLength
   found for class: java.lang.Long
```
The equivalent:
`(t/<< (t/clock) (t/new-duration 2 :hours))`
would work.

**Comment by henryw374** [comment]
Think this is fixed - see referenced commits in this issue.
