### ISSUE TITLE
The example of setting clock granularity does not work in the document

### ISSUE THREAD

**Issue by yubrshen** [juxt/tick#93]
In the document https://github.com/juxt/tick/blob/master/docs/clocks.adoc

The example of 
`(def minute-clk (tick (clock) (minutes 1)))`
with the error
```
1. Caused by java.lang.RuntimeException
   No such var: tick
```
Maybe, 
`(minutes 1)`
will also fail for duration value.

**Comment by henryw374** [comment]
Thanks. The docs for this have been fixed up
