### ISSUE TITLE
No easy way to pretty-print a duration?

### ISSUE THREAD

**Issue by WhittlesJr** [juxt/tick#99]
When I was using joda, I was able to do this to get a nice, pretty duration string:

```clojure
(def period-format (PeriodFormat/getDefault))

(defn duration-str [time-a time-b]
   (->> (time/interval time-a time-b)
      (.toPeriod)
      (.print period-format)))
```

I'm struggling to find a clean, out-of-the-box replacement for this, especially if I want it to print years, months, and days as well as hours, minutes, and seconds. Am I missing something, or is my best option right now doing a bunch of math?

**Comment by henryw374** [comment]
periods and durations are different things in java.time. 

Once you've decided which, I expect stackoverflow will be your best bet. if it's a datetimeformatter you need there is t/formatter sugar

**Comment by henryw374** [comment]
Not heard back on this for a while... closing
